### ISSUE TITLE
Create azure-core

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#119]
Contains all common infrastructure needed to process the request pipeline.

**Azure.Core**
- [x] Define HTTP Pipeline Architecture (@anuchandy, @bsiegel, @vcolin7)
- [x] Implement HTTP Pipeline (@anuchandy)
  - [x] Implement basic HTTP Pipeline with OkHttp + Retrofit #132
  - [x] Pipeline configuration #145
  - [x] JSON / XML serializer adapter #125
  - [x] Write deserializers for thirteenabp Duration and DateTimeOffset types #144
  - [x] Error handling #126
- [x] Implement HTTP Pipeline Interceptors
  - [x] Request modification (@vcolin7) #133
    - [x] User agent policy
    - [x] Request ID policy
    - [x] Add date policy
  - [x] Credentials (@anuchandy)
    - [x] Generic token provider interface & policies #134
  - [x] Response modification (@vcolin7) #136
    - [x] Response validation policy
    - [x] Scrub eTag policy
  - [x] Logging (@vcolin7) #127
    - [x] Logger interface
    - [x] HTTP logger policy
    - [x] cURL-formatted logger policy
- [ ] Define paging architecture (@anuchandy, @bsiegel, @vcolin7) #130
- [ ] Implement paging (@vcolin7) #138

**Comment by vcolin7** [comment]
Updated the checklist to add who is working on the interceptors.

**Comment by bsiegel** [comment]
Closing in favor of remaining child tasks.
