### ISSUE TITLE
Create azure-storage-blob

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#121]
Create an storage-blob library with functionality from the Java version of azure-storage-blob that makes sense for mobile. This does not include the creation of any higher-level transfer manager code, this is just the REST bindings.

- [x] Download blob #194
- [x] Upload blob #182
- [x] List blobs in container
- [ ] Remove blob #195

**Comment by vcolin7** [comment]
Stories we can break this Epic into:

- [ ] Define operations to be supported by Storage Blob. Tentatively:
    - Upload
    - Download
- [ ] Come up with public sync API proposal
- [ ] Implement proposed API including underlying private and protected models and classes
- [ ] Create unit and integration tests

**Comment by bsiegel** [comment]
Updated description and added "list blobs", thanks!
