### ISSUE TITLE
Create blob transfer manager

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#122]
Create a transfer manager for blob storage. This includes significant architecture work to determine what functionality needs to be provided.

## Basic operations
- [x] Determine the range of the operations TransferManager will support: #196
  - track transfer progress
  - pause transfer
  - resume transfer
  - cancel transfer
  - get active transfers
- [x] Define how TransferManager will interface with the Storage Blob APIs #196
- [x] Define the mechanism by which TransferManager will re-auth and under what conditions it will do so #196
- [x] Implement download block #197
- [x] Implement upload block #196

## Persistence
- [x] Define how TransferManager will persist the operation queue across app runs #196
- [x] Implement blob transfer #196 #197
- [ ] Implement multi-blob transfer #196 #197

## Caching
- [x] Determine how / when TransferManager will cache content #196
- [x] Implement local cache management #196

## After Preview 1
- [ ] Define how TransferManager will interface with the OS to run transfers in the background

**Comment by vcolin7** [comment]
Stories we can break this Epic into on a high level:

- [ ] Determine the range of the operations TransferManager will support: track transfer progress, pause transfer, resume transfer, cancel transfer, etc.
- [ ] Define how TransferManager will interface with the Storage Blob APIs.
- [ ] Define if TransferManager will be responsible of some retrying/autorization tasks and how much, e.g. refreshing a SAS token once it has expired if a transfer is not complete and retrying/resuming the operation.
- [ ] Come up with public API proposal
- [ ] Implement proposed API including underlying private and protected models and classes
- [ ] Create unit and integration tests

**Comment by bsiegel** [comment]
Updated description and expanded upon some of the tasks, thanks!
