### ISSUE TITLE
Create azure-cs-computervision

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#146]
Create a cognitive services - computer vision library with functionality from the Java version of azure-cs-computervision that makes sense for mobile.

- [ ] Define operations to be supported by cs-computervision.
- [ ] Come up with public sync API proposal
- [ ] Implement proposed API including underlying private and protected models and classes
- [ ] Create unit and integration tests
