### ISSUE TITLE
Create azure-cs-textanalytics

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#147]
Create a cognitive services - text analytics library with functionality from the Java version of azure-cs-textanalytics that makes sense for mobile.

- [ ] Define operations to be supported by cs-textanalytics.
- [ ] Come up with public sync API proposal
- [ ] Implement proposed API including underlying private and protected models and classes
- [ ] Create unit and integration tests
