### ISSUE TITLE
EngSys for Android repository

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-android#149]
We need to establish the baseline engineering system for the Android repository. Looking at the capabilities of our other repos here are some of the capabilties/services that we need to get up and running.

- [x] Separate pipeline per service directory (e.g. ```sdk/[service]```)
- [x] Run build to validate that code compiles
- [x] Run tests (on agent or emulator?) against supported targets #251
- [x] Run analyze step with common steps and additional quality checks
- [x] Setup release gates with approvals
- [x] Automate release of packages to Maven
- [x] Establish ```sdk/template``` for testing of pipeline and copy-paste.

**Comment by mitchdenny** [comment]
I've got a bunch of changes queued up to support building and releasing packages for Android. These need to get merged before I can move onto the next steps. Importantly I haven't actually done an rc-release to Maven yet (although I've staged successfully). The reason is that I didn't want to actually push out com.azure.android:azure-core even in a beta form until we were ready.

One thing that I want to do as soon as the changes from #181 and https://github.com/Azure/azure-sdk-for-java/pull/8025 are merged is setup a template library in the Android library so we can get end-to-end - but at this point I'm pretty confident we won't have an issue.
