### ISSUE TITLE
[FEATURE REQ]

### ISSUE THREAD

**Issue by notebook-t** [Azure/azure-sdk-for-android#1699]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-android/pull/1698
- [ ] https://github.com/Azure/azure-sdk-for-android/pull/1695
```
