### ISSUE TITLE
Release Track 2 SDK Preview 1 for Android

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#187]
Release checklist:
- [ ] Core #119 ~85% progress
- [ ] Identity MSAL #120 ~60% progress
- [ ] Identity Pre-Authenticated URL provider
- [x] Storage upload #182
- [x] Storage download #194
- [x] Storage list #236
- [x] Storage delete #195
- [x] TM upload #196
- [x] TM download #197
- [x] TM Queue Management #122
- [x] TM Persistence #122
- [ ] ~TM Caching #122~ Not planned for preview 1.
- [ ] ~TM Aggregate Operations #122~ Not planned for preview 1.
- [ ] Resolve TODOs / lints #192
- [ ] Public API review #191
- [ ] API docs #190
- [ ] Build system #149
- [ ] Release packaging #149
- [x] Test coverage #189
- [ ] READMEs #193
- [ ] ~UX study #188~ Not planned for preview 1.
- [ ] Blog post
